create database Const_13;
use  Const_13;

create table ZIPCODE_INFO(
ZIP_CODE VARCHAR(5),
CITY VARCHAR(10)
);


 create table INSTRUCTOR_INFO(
 INSTRUCTOR_ID NUMERIC (8,0),
 INSTRUCTOR_FIRST_NAME VARCHAR(15),
 INSTRUCTOR_LAST_NAME VARCHAR(15)
 );
 
 
 create table COURSE_INFO(
 COURSE_NO NUMERIC (8,0),
 COST NUMERIC (5,2)
 );
 
 
 create table STUDENT_INFO(
 STUDENT_ID NUMERIC (8,0),
 STUDENT_FIRST_NAME VARCHAR (15),
 STUDENT_LAST_NAME VARCHAR (15)
 );
 
 
create table SECTION_INFO(
 SECTION_ID NUMERIC (8,0),
 COURSE_NO NUMERIC (8,0),
 SECTION_NO NUMERIC (5,0),
 INSTRUCTOR_ID NUMERIC (8,0)
 );
 
  
create table ENROLLMENT_INFO(
 STUDENT_ID NUMERIC (8,0),
 SECTION_ID NUMERIC (8,0)
 );
 

 create table GRADE_INFO(
 STUDENT_ID NUMERIC (8,0),
 SECTION_ID NUMERIC (8,0),
 GRADE_TYPE_CODE CHAR (2),
 GRADE_CODE_OCCURANCE NUMERIC (5)
 );
 
 
 --ZIPCODE_INFO
 
 
 alter table zipcode_info
alter column zip_code varchar(5) not null;
 
 alter table zipcode_info
 add constraint zip_pk primary key (zip_code);
 
 alter table zipcode_info 
add constraint ZIP_CITY_NN check(city is not null)

alter table zipcode_info
add state varchar(2)

alter table zipcode_info
add constraint ZIP_STATE_NN check (state is not null)
 
--INSTRUCTOR_INFO

alter table INSTRUCTOR_INFO
add STREET_ADDRESS VARCHAR(50),
ZIP_CODE VARCHAR(5);

alter table INSTRUCTOR_INFO
alter column INSTRUCTOR_ID NUMERIC (8,0) not null;

alter table INSTRUCTOR_INFO
add constraint  INSTRUCTOR_ID_PK PRIMARY KEY (INSTRUCTOR_ID);

alter table INSTRUCTOR_INFO
add constraint INSTRUCTOR_FN_NN check (INSTRUCTOR_FIRST_NAME is not null)

alter table INSTRUCTOR_INFO
add constraint INSTRUCTOR_LN_NN check (INSTRUCTOR_LAST_NAME is not NULL )

alter table INSTRUCTOR_INFO
add constraint ZIP_INSTRUCTOR_FK 
foreign key(ZIP_CODE)
REFERENCES   ZIPCODE_INFO(ZIP_CODE);


-- Add missing columns
ALTER TABLE COURSE_INFO
ADD COURSE_NAME VARCHAR(50),
    COURSE_PREREQUISITE NUMERIC(8,0);

-- Constraints
ALTER TABLE COURSE_INFO
ADD CONSTRAINT COURSE_NO_PK PRIMARY KEY (COURSE_NO);

ALTER TABLE COURSE_INFO
ADD CONSTRAINT COURSE_NAME_NN CHECK (COURSE_NAME IS NOT NULL);

ALTER TABLE COURSE_INFO
ADD CONSTRAINT COST_NN CHECK (COST IS NOT NULL);



-- Add missing columns
ALTER TABLE STUDENT_INFO
ADD STREET_ADDRESS VARCHAR(50),
    ZIP_CODE VARCHAR(5);

-- Constraints
ALTER TABLE STUDENT_INFO
ADD CONSTRAINT STUDENT_ID_PK PRIMARY KEY (STUDENT_ID);

ALTER TABLE STUDENT_INFO
ADD CONSTRAINT STUDENT_FN_NN CHECK (STUDENT_FIRST_NAME IS NOT NULL);

ALTER TABLE STUDENT_INFO
ADD CONSTRAINT STUDENT_LN_NN CHECK (STUDENT_LAST_NAME IS NOT NULL);

ALTER TABLE STUDENT_INFO
ADD CONSTRAINT ZIP_STUDENT_FK
FOREIGN KEY (ZIP_CODE)
REFERENCES ZIPCODE_INFO(ZIP_CODE);




-- Add missing columns
ALTER TABLE SECTION_INFO
ADD LOCATION VARCHAR(50),
    CAPACITY NUMERIC(3,0);

-- Constraints
ALTER TABLE SECTION_INFO
ADD CONSTRAINT SECTION_ID_PK PRIMARY KEY (SECTION_ID);

ALTER TABLE SECTION_INFO
ADD CONSTRAINT SECTION_NO_NN CHECK (SECTION_NO IS NOT NULL);

ALTER TABLE SECTION_INFO
ADD CONSTRAINT COURSE_SECTION_FK
FOREIGN KEY (COURSE_NO)
REFERENCES COURSE_INFO(COURSE_NO);

ALTER TABLE SECTION_INFO
ADD CONSTRAINT INSTRUCTOR_SECTION_FK
FOREIGN KEY (INSTRUCTOR_ID)
REFERENCES INSTRUCTOR_INFO(INSTRUCTOR_ID);



-- Add missing column
ALTER TABLE ENROLLMENT_INFO
ADD ENROLLMENT_DATE DATE;

-- Constraints
ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_STUD_SECT_PK
PRIMARY KEY (STUDENT_ID, SECTION_ID);

ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_STUDENT_ID_FK
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT_INFO(STUDENT_ID);

ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_SECTION_ID_FK
FOREIGN KEY (SECTION_ID)
REFERENCES SECTION_INFO(SECTION_ID);



-- Add missing column
ALTER TABLE GRADE_INFO
ADD NUMERIC_GRADE NUMERIC(3,0) DEFAULT 0;

-- Composite Primary Key
ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_STUD_SECT_TYPE_CODE_PK
PRIMARY KEY (STUDENT_ID, SECTION_ID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE);

-- Foreign Keys
ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_STUDENT_ID_FK
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT_INFO(STUDENT_ID);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_SECTION_ID_FK
FOREIGN KEY (SECTION_ID)
REFERENCES SECTION_INFO(SECTION_ID);

-- Check constraint
ALTER TABLE GRADE_INFO
ADD CONSTRAINT CHK_GRADE_TYPE_CODE
CHECK (GRADE_TYPE_CODE IN ('FI','HM','MT','PA','PJ','QZ'));
 